# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

warnings_are_errors: false

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"

deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    project: schumpermas
    message: $TRAVIS_COMMIT_MESSAGE
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local-dir: _book/
    github-token: $GITHUB_TOKEN
    on:
      branch: master
notifications:
  email: false
